import type { Locale } from "./i18n";

export type BusinessTool = { slug:string; icon:string; title:string; desc:string };

type ForeignLocale = Exclude<Locale,"ja">;

export const businessHubCopy: Record<ForeignLocale,{title:string;lead:string;group:string;groupLead:string}> = {
  en:{title:"Free Business Tools",lead:"Practical calculators and text utilities for work, ecommerce and marketing. No signup required.",group:"Business / EC / Marketing",groupLead:"Small, fast tools for calculations, text cleanup, ecommerce operations and advertising."},
  "zh-tw":{title:"免費工作工具",lead:"工作、電商與行銷常用的計算與文字整理工具，免註冊即可使用。",group:"工作・EC・行銷",groupLead:"快速完成計算、文字整理、電商營運與廣告分析的小工具。"},
  "zh-cn":{title:"免费工作工具",lead:"适用于工作、电商与营销的计算和文本整理工具，无需注册即可使用。",group:"工作・电商・营销",groupLead:"快速完成计算、文本整理、电商运营和广告分析的小工具。"},
  ko:{title:"무료 업무 도구",lead:"업무, 이커머스, 마케팅에 자주 쓰는 계산기와 텍스트 도구입니다. 가입 없이 사용할 수 있습니다.",group:"업무・EC・마케팅",groupLead:"계산, 문장 정리, EC 운영, 광고 분석을 빠르게 처리하는 도구입니다."},
  th:{title:"เครื่องมือธุรกิจฟรี",lead:"เครื่องมือคำนวณและจัดการข้อความสำหรับงาน อีคอมเมิร์ซ และการตลาด ใช้ได้โดยไม่ต้องสมัคร",group:"ธุรกิจ / EC / การตลาด",groupLead:"เครื่องมือเล็ก ๆ สำหรับการคำนวณ จัดข้อความ งานอีคอมเมิร์ซ และวิเคราะห์โฆษณา"},
  id:{title:"Alat Bisnis Gratis",lead:"Kalkulator dan utilitas teks untuk pekerjaan, ecommerce, dan marketing. Bisa digunakan tanpa registrasi.",group:"Bisnis / EC / Marketing",groupLead:"Alat cepat untuk perhitungan, merapikan teks, operasional ecommerce, dan analisis iklan."}
};

const en:BusinessTool[]=[
 {slug:"date-calculator",icon:"日",title:"Date Calculator",desc:"Add or subtract days and calculate the difference between two dates."},
 {slug:"gross-profit",icon:"粗",title:"Gross Profit Calculator",desc:"Calculate gross profit, margin and cost ratio from selling price and cost."},
 {slug:"text-counter",icon:"字",title:"Character & Line Counter",desc:"Count characters, characters without spaces and lines in real time."},
 {slug:"dedupe-lines",icon:"重",title:"Remove Duplicate Lines",desc:"Remove duplicate lines while keeping the original order."},
 {slug:"postal-code",icon:"〒",title:"Japan Postal Code Lookup",desc:"Look up Japanese addresses from postal codes and postal codes from addresses."},
 {slug:"mojibake",icon:"文",title:"Mojibake Repair",desc:"Try to repair common UTF-8 text encoding corruption in your browser."},
 {slug:"password-generator",icon:"PW",title:"Password Generator",desc:"Generate random passwords with your preferred length and character types."},
 {slug:"html-entities",icon:"&",title:"HTML Entity Converter",desc:"Encode and decode HTML entities."},
 {slug:"age-table",icon:"年",title:"Age & Birth Year Calculator",desc:"Calculate age from a birth date or estimate a birth year from a current age."},
 {slug:"text-sort",icon:"↕",title:"Text Sorter",desc:"Sort lines ascending, descending, numerically or randomly."},
 {slug:"sku-generator",icon:"SKU",title:"Sequential SKU Generator",desc:"Generate many SKU codes from a prefix, start number, digits and quantity."},
 {slug:"zenkaku-hankaku",icon:"Aa",title:"Full-width to Half-width Converter",desc:"Convert full-width Latin letters, numbers and spaces to half-width."},
 {slug:"trim-spaces",icon:"SP",title:"Whitespace Cleaner",desc:"Remove leading, trailing and repeated spaces and line-end whitespace."},
 {slug:"tax-calculator",icon:"税",title:"Tax Included / Excluded Calculator",desc:"Calculate tax-included, tax-excluded and tax amounts with a selected rate."},
 {slug:"price-change-rate",icon:"%",title:"Price Change Rate Calculator",desc:"Calculate price increase/decrease rate and amount from before and after prices."},
 {slug:"roas",icon:"R",title:"ROAS Calculator",desc:"Calculate return on ad spend from advertising cost and attributed revenue."},
 {slug:"roi",icon:"ROI",title:"ROI Calculator",desc:"Calculate ROI from investment and profit."},
 {slug:"marketing-kpi",icon:"KPI",title:"CPA / CVR / CTR Calculator",desc:"Calculate common advertising KPIs including CPA, CVR and CTR."}
];

const zhTw:BusinessTool[]=[
 {slug:"date-calculator",icon:"日",title:"日期計算工具",desc:"日期加減天數，並計算兩個日期之間的差距。"},{slug:"gross-profit",icon:"粗",title:"毛利計算工具",desc:"由售價與成本計算毛利額、毛利率與成本率。"},{slug:"text-counter",icon:"字",title:"字數・行數計算",desc:"即時計算字數、不含空白字數與行數。"},{slug:"dedupe-lines",icon:"重",title:"刪除重複行",desc:"保留原順序並刪除重複文字行。"},{slug:"postal-code",icon:"〒",title:"日本郵遞區號查詢",desc:"可由郵遞區號查日本地址，也可由地址查郵遞區號。"},{slug:"mojibake",icon:"文",title:"亂碼修復",desc:"在瀏覽器中嘗試修復常見的 UTF-8 文字亂碼。"},{slug:"password-generator",icon:"PW",title:"密碼產生器",desc:"指定長度與字元種類來產生隨機密碼。"},{slug:"html-entities",icon:"&",title:"HTML 實體轉換",desc:"HTML 實體編碼與解碼。"},{slug:"age-table",icon:"年",title:"年齡・出生年計算",desc:"由生日計算年齡，或由目前年齡推算出生年份。"},{slug:"text-sort",icon:"↕",title:"文字排序工具",desc:"依升冪、降冪、數字或隨機方式排列文字行。"},{slug:"sku-generator",icon:"SKU",title:"連號 SKU 產生器",desc:"依前綴、起始號碼、位數與數量批次產生 SKU。"},{slug:"zenkaku-hankaku",icon:"Aa",title:"全形英數轉半形",desc:"將全形英文字母、數字與空白一次轉成半形。"},{slug:"trim-spaces",icon:"SP",title:"多餘空白清理",desc:"移除前後空白、連續空白與行尾空白。"},{slug:"tax-calculator",icon:"税",title:"含稅・未稅計算",desc:"依指定稅率計算含稅、未稅與稅額。"},{slug:"price-change-rate",icon:"%",title:"漲價・降價率計算",desc:"由變更前後價格計算漲跌幅與差額。"},{slug:"roas",icon:"R",title:"ROAS 計算",desc:"由廣告費與廣告營收計算 ROAS。"},{slug:"roi",icon:"ROI",title:"ROI 計算",desc:"由投資額與利潤計算 ROI。"},{slug:"marketing-kpi",icon:"KPI",title:"CPA・CVR・CTR 計算",desc:"一次計算廣告常用的 CPA、CVR、CTR。"}
];
const zhCn=zhTw.map(x=>({...x,title:x.title.replaceAll("計算","计算").replaceAll("工具","工具").replaceAll("亂碼","乱码").replaceAll("刪除","删除").replaceAll("郵遞區號","邮政编码").replaceAll("產生器","生成器").replaceAll("全形","全角").replaceAll("半形","半角").replaceAll("空白","空格").replaceAll("漲價","涨价").replaceAll("降價","降价"),desc:x.desc.replaceAll("計算","计算").replaceAll("郵遞區號","邮政编码").replaceAll("亂碼","乱码").replaceAll("產生","生成").replaceAll("全形","全角").replaceAll("半形","半角").replaceAll("空白","空格").replaceAll("廣告","广告").replaceAll("營收","营收").replaceAll("額","额")}));

const ko:BusinessTool[]=[
 {slug:"date-calculator",icon:"日",title:"날짜 계산기",desc:"날짜에 일수를 더하거나 빼고 두 날짜 사이의 차이를 계산합니다."},{slug:"gross-profit",icon:"粗",title:"매출총이익 계산기",desc:"판매가와 원가로 매출총이익, 이익률, 원가율을 계산합니다."},{slug:"text-counter",icon:"字",title:"글자 수・줄 수 계산",desc:"글자 수, 공백 제외 글자 수, 줄 수를 실시간으로 표시합니다."},{slug:"dedupe-lines",icon:"重",title:"중복 줄 제거",desc:"원래 순서를 유지하면서 중복된 줄을 제거합니다."},{slug:"postal-code",icon:"〒",title:"일본 우편번호 검색",desc:"우편번호로 일본 주소를 찾거나 주소로 우편번호를 검색합니다."},{slug:"mojibake",icon:"文",title:"문자 깨짐 복구",desc:"일반적인 UTF-8 인코딩 문자 깨짐을 브라우저에서 복구합니다."},{slug:"password-generator",icon:"PW",title:"비밀번호 생성기",desc:"길이와 문자 종류를 지정해 임의 비밀번호를 생성합니다."},{slug:"html-entities",icon:"&",title:"HTML 엔티티 변환",desc:"HTML 엔티티를 인코딩・디코딩합니다."},{slug:"age-table",icon:"年",title:"나이・출생연도 계산기",desc:"생년월일로 나이를 계산하거나 현재 나이로 출생연도를 추정합니다."},{slug:"text-sort",icon:"↕",title:"텍스트 정렬",desc:"줄 단위로 오름차순, 내림차순, 숫자순, 무작위 정렬합니다."},{slug:"sku-generator",icon:"SKU",title:"연속 SKU 생성기",desc:"접두사, 시작 번호, 자릿수, 개수를 지정해 SKU를 일괄 생성합니다."},{slug:"zenkaku-hankaku",icon:"Aa",title:"전각 영숫자 → 반각",desc:"전각 영문・숫자・공백을 반각으로 변환합니다."},{slug:"trim-spaces",icon:"SP",title:"불필요한 공백 제거",desc:"앞뒤 공백, 연속 공백, 줄 끝 공백을 정리합니다."},{slug:"tax-calculator",icon:"税",title:"세금 포함・별도 계산기",desc:"세율을 지정해 세금 포함 금액, 세전 금액, 세액을 계산합니다."},{slug:"price-change-rate",icon:"%",title:"가격 인상・인하율 계산",desc:"변경 전후 가격에서 변화율과 차액을 계산합니다."},{slug:"roas",icon:"R",title:"ROAS 계산기",desc:"광고비와 광고 매출로 ROAS를 계산합니다."},{slug:"roi",icon:"ROI",title:"ROI 계산기",desc:"투자액과 이익으로 ROI를 계산합니다."},{slug:"marketing-kpi",icon:"KPI",title:"CPA・CVR・CTR 계산",desc:"광고 운영에 자주 쓰는 CPA, CVR, CTR을 함께 계산합니다."}
];
const th:BusinessTool[]=[
 {slug:"date-calculator",icon:"日",title:"คำนวณวันที่",desc:"บวกหรือลบจำนวนวัน และหาความต่างระหว่างสองวันที่"},{slug:"gross-profit",icon:"粗",title:"คำนวณกำไรขั้นต้น",desc:"คำนวณกำไรขั้นต้น อัตรากำไร และอัตราต้นทุนจากราคาขายและต้นทุน"},{slug:"text-counter",icon:"字",title:"นับตัวอักษรและบรรทัด",desc:"นับตัวอักษร ตัวอักษรไม่รวมช่องว่าง และจำนวนบรรทัดแบบเรียลไทม์"},{slug:"dedupe-lines",icon:"重",title:"ลบบรรทัดซ้ำ",desc:"ลบบรรทัดที่ซ้ำโดยคงลำดับเดิม"},{slug:"postal-code",icon:"〒",title:"ค้นหารหัสไปรษณีย์ญี่ปุ่น",desc:"ค้นหาที่อยู่ญี่ปุ่นจากรหัสไปรษณีย์ หรือค้นหารหัสจากที่อยู่"},{slug:"mojibake",icon:"文",title:"แก้ข้อความเพี้ยน",desc:"ลองแก้ข้อความเพี้ยนจากการเข้ารหัส UTF-8 ที่พบบ่อยในเบราว์เซอร์"},{slug:"password-generator",icon:"PW",title:"สร้างรหัสผ่าน",desc:"สร้างรหัสผ่านสุ่มโดยกำหนดความยาวและชนิดตัวอักษร"},{slug:"html-entities",icon:"&",title:"แปลง HTML Entity",desc:"เข้ารหัสและถอดรหัส HTML Entity"},{slug:"age-table",icon:"年",title:"คำนวณอายุและปีเกิด",desc:"คำนวณอายุจากวันเกิด หรือประมาณปีเกิดจากอายุปัจจุบัน"},{slug:"text-sort",icon:"↕",title:"เรียงข้อความ",desc:"เรียงบรรทัดจากน้อยไปมาก มากไปน้อย แบบตัวเลข หรือสุ่ม"},{slug:"sku-generator",icon:"SKU",title:"สร้าง SKU แบบลำดับ",desc:"สร้าง SKU หลายรายการจากคำนำหน้า เลขเริ่มต้น จำนวนหลัก และจำนวนรายการ"},{slug:"zenkaku-hankaku",icon:"Aa",title:"แปลงอักขระ Full-width",desc:"แปลงตัวอักษรอังกฤษ ตัวเลข และช่องว่างแบบ full-width เป็น half-width"},{slug:"trim-spaces",icon:"SP",title:"ล้างช่องว่างส่วนเกิน",desc:"ลบช่องว่างต้นท้าย ช่องว่างซ้ำ และช่องว่างท้ายบรรทัด"},{slug:"tax-calculator",icon:"税",title:"คำนวณราคารวม/ไม่รวมภาษี",desc:"คำนวณราคารวมภาษี ราคาก่อนภาษี และภาษีตามอัตราที่เลือก"},{slug:"price-change-rate",icon:"%",title:"คำนวณอัตราการเปลี่ยนราคา",desc:"คำนวณเปอร์เซ็นต์เพิ่ม/ลดและส่วนต่างจากราคาก่อนและหลัง"},{slug:"roas",icon:"R",title:"คำนวณ ROAS",desc:"คำนวณ ROAS จากค่าโฆษณาและยอดขายจากโฆษณา"},{slug:"roi",icon:"ROI",title:"คำนวณ ROI",desc:"คำนวณ ROI จากเงินลงทุนและกำไร"},{slug:"marketing-kpi",icon:"KPI",title:"คำนวณ CPA・CVR・CTR",desc:"คำนวณ KPI โฆษณาที่ใช้บ่อย ได้แก่ CPA, CVR และ CTR"}
];
const id:BusinessTool[]=[
 {slug:"date-calculator",icon:"日",title:"Kalkulator Tanggal",desc:"Tambah atau kurangi hari dan hitung selisih antara dua tanggal."},{slug:"gross-profit",icon:"粗",title:"Kalkulator Laba Kotor",desc:"Hitung laba kotor, margin, dan rasio biaya dari harga jual dan biaya."},{slug:"text-counter",icon:"字",title:"Penghitung Karakter & Baris",desc:"Hitung karakter, karakter tanpa spasi, dan baris secara real time."},{slug:"dedupe-lines",icon:"重",title:"Hapus Baris Duplikat",desc:"Hapus baris duplikat sambil mempertahankan urutan asli."},{slug:"postal-code",icon:"〒",title:"Pencarian Kode Pos Jepang",desc:"Cari alamat Jepang dari kode pos atau kode pos dari alamat."},{slug:"mojibake",icon:"文",title:"Perbaikan Teks Rusak",desc:"Coba perbaiki kerusakan encoding UTF-8 yang umum di browser."},{slug:"password-generator",icon:"PW",title:"Generator Password",desc:"Buat password acak dengan panjang dan jenis karakter yang dipilih."},{slug:"html-entities",icon:"&",title:"Konverter HTML Entity",desc:"Encode dan decode HTML entity."},{slug:"age-table",icon:"年",title:"Kalkulator Usia & Tahun Lahir",desc:"Hitung usia dari tanggal lahir atau perkiraan tahun lahir dari usia saat ini."},{slug:"text-sort",icon:"↕",title:"Pengurut Teks",desc:"Urutkan baris naik, turun, numerik, atau acak."},{slug:"sku-generator",icon:"SKU",title:"Generator SKU Berurutan",desc:"Buat banyak SKU dari prefix, nomor awal, jumlah digit, dan jumlah item."},{slug:"zenkaku-hankaku",icon:"Aa",title:"Konverter Full-width ke Half-width",desc:"Ubah huruf Latin, angka, dan spasi full-width menjadi half-width."},{slug:"trim-spaces",icon:"SP",title:"Pembersih Spasi",desc:"Hapus spasi awal/akhir, spasi berulang, dan spasi di akhir baris."},{slug:"tax-calculator",icon:"税",title:"Kalkulator Termasuk / Belum Pajak",desc:"Hitung nilai termasuk pajak, sebelum pajak, dan jumlah pajak."},{slug:"price-change-rate",icon:"%",title:"Kalkulator Perubahan Harga",desc:"Hitung persentase kenaikan/penurunan dan selisih harga."},{slug:"roas",icon:"R",title:"Kalkulator ROAS",desc:"Hitung ROAS dari biaya iklan dan omzet dari iklan."},{slug:"roi",icon:"ROI",title:"Kalkulator ROI",desc:"Hitung ROI dari investasi dan laba."},{slug:"marketing-kpi",icon:"KPI",title:"Kalkulator CPA・CVR・CTR",desc:"Hitung KPI iklan umum termasuk CPA, CVR, dan CTR."}
];

export const businessToolsByLocale:Record<ForeignLocale,BusinessTool[]>={en,"zh-tw":zhTw,"zh-cn":zhCn,ko,th,id};
export const BUSINESS_TOOL_SLUGS=en.map(x=>x.slug);
export function getBusinessTool(locale:ForeignLocale,slug:string){return businessToolsByLocale[locale].find(x=>x.slug===slug);}
