import stickers from "../data/stickers.json";
import designs from "../data/suzuri-designs.json";
import { CATEGORY_DEFINITIONS,getCategory,SITE_URL } from "../lib/stickers";
import { LOCALES, localeInfo, localizedPath } from "../lib/i18n";
import { BUSINESS_TOOL_SLUGS } from "../lib/business-tools-i18n";
import { getTagIdsForSticker,getTagPath,tagDefinitions } from "../lib/sticker-search-tags";
const PAGE_SIZE=24; type Locale=(typeof LOCALES)[number];
function escapeXml(value:string){return value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&apos;");}
function pagePath(path:string){if(!path||path==="/")return "/";const clean=path.split(/[?#]/,1)[0];if(/\/[^/]+\.[a-z0-9]{1,16}$/i.test(clean))return path;return path.endsWith("/")?path:`${path}/`;}
function localizedUrl(locale:Locale,path:string){return `${SITE_URL}${localizedPath(locale,pagePath(path))}`;}
function renderUrlEntry(currentUrl:string,alts:Record<Locale,string>,x:string){const links=LOCALES.map(l=>`    <xhtml:link rel="alternate" hreflang="${localeInfo[l].htmlLang}" href="${escapeXml(alts[l])}" />`).join("\n");return `  <url>\n    <loc>${escapeXml(currentUrl)}</loc>\n${links}\n    <xhtml:link rel="alternate" hreflang="x-default" href="${escapeXml(x)}" />\n  </url>`;}
function multilingualEntries(path:string){const normalized=pagePath(path);const urls=Object.fromEntries(LOCALES.map(l=>[l,localizedUrl(l,normalized)])) as Record<Locale,string>;return LOCALES.map(l=>renderUrlEntry(urls[l],urls,urls.ja));}
function multilingualTagEntries(tag:(typeof tagDefinitions)[number]){const urls=Object.fromEntries(LOCALES.map(l=>[l,`${SITE_URL}${pagePath(getTagPath(l,tag))}`])) as Record<Locale,string>;return LOCALES.map(l=>renderUrlEntry(urls[l],urls,urls.ja));}
export function GET(){const entries:string[]=[];for(const p of ["/","/news/","/goods/","/tags/","/qr-maker/","/chat-stamp-maker/","/image-compressor/","/image-resizer/","/convert-to-jpg/","/jpg-to-image/","/png-transparent/","/seal-maker/","/tools/","/chat-icons/","/categories/"])entries.push(...multilingualEntries(p));for(const slug of BUSINESS_TOOL_SLUGS)entries.push(...multilingualEntries(`/tools/${slug}/`));entries.push(`  <url><loc>${escapeXml(`${SITE_URL}/color-palette/`)}</loc></url>`);for(const s of stickers){entries.push(...multilingualEntries(`/stickers/${encodeURIComponent(s.id)}/`));entries.push(...multilingualEntries(`/chat-icons/${encodeURIComponent(s.id)}/`));}for(const d of designs)entries.push(...multilingualEntries(`/goods/${encodeURIComponent(String(d.id))}/`));for(const tag of tagDefinitions){const count=stickers.filter(s=>getTagIdsForSticker(s).includes(tag.id)).length;if(count>=2)entries.push(...multilingualTagEntries(tag));}for(const c of CATEGORY_DEFINITIONS){const count=stickers.filter(s=>getCategory(s)===c.name).length,total=Math.max(1,Math.ceil(count/PAGE_SIZE));for(let p=1;p<=total;p++)entries.push(...multilingualEntries(`/categories/${c.slug}/${p}/`));}return new Response(`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n${entries.join("\n")}\n</urlset>`,{headers:{"Content-Type":"application/xml; charset=utf-8","Cache-Control":"public, max-age=0, s-maxage=3600"}});}
