import crypto from "node:crypto";
import { r2GetJson, r2PutJson } from "./_r2.js";

const INDEX_KEY = "chat-stamps/index.json";
const MAX_ITEMS = 500;
const MAX_TEXT = 32;
const allowedStyles = new Set(["business", "pop", "stamp", "bold", "soft", "mono"]);
const allowedLayouts = new Set(["horizontal", "vertical"]);
const allowedLineModes = new Set(["auto", "1", "2", "3", "4"]);
const allowedEffects = new Set(["none", "shadow", "glow", "depth"]);
const allowedBackgrounds = new Set(["transparent", "white", "color"]);
const allowedFonts = new Set(["gothic","rounded","mincho","serif","hand","pop","retro","bold","classic","casual"]);
const allowedStampShapes = new Set(["rounded", "circle"]);

function normalizeText(value){return String(value||"").normalize("NFKC").replace(/\r\n?/g,"\n").replace(/[\u0000-\u0009\u000B\u000C\u000E-\u001F\u007F]/g,"").trim().slice(0,MAX_TEXT)}
function safeColor(value,fallback){const v=String(value||"").trim();return /^#[0-9a-fA-F]{6}$/.test(v)?v.toLowerCase():fallback}
function clampNumber(value,min,max,fallback){const n=Number(value);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback}
function safeSettings(raw={}){return{lineMode:allowedLineModes.has(String(raw.lineMode))?String(raw.lineMode):"auto",font:allowedFonts.has(raw.font)?raw.font:"gothic",textColor:safeColor(raw.textColor,"#111827"),strokeEnabled:raw.strokeEnabled!==false,strokeColor:safeColor(raw.strokeColor,"#ffffff"),strokeWidth:clampNumber(raw.strokeWidth,0,28,14),effect:allowedEffects.has(raw.effect)?raw.effect:"none",background:allowedBackgrounds.has(raw.background)?raw.background:"transparent",backgroundColor:safeColor(raw.backgroundColor,"#fff3f7"),fontScale:clampNumber(raw.fontScale,60,160,100),letterSpacing:clampNumber(raw.letterSpacing,-12,42,0),horizontalScale:clampNumber(raw.horizontalScale,50,130,100),rotation:clampNumber(raw.rotation,-30,30,0),padding:clampNumber(raw.padding,0,20,5),stampShape:allowedStampShapes.has(raw.stampShape)?raw.stampShape:"rounded"}}
function safetyCheck(raw){const text=normalizeText(raw);if(!text)return{level:"red",reason:"文字を入力してください"};const flattened=text.replace(/\n/g," ");const red=[/(?:https?:\/\/|www\.)/i,/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i,/(?:\+?81[- ]?)?0\d{1,4}[- ]?\d{1,4}[- ]?\d{3,4}/,/\b(?:\d[ -]?){12,19}\b/,/(?:パスワード|暗証番号|社外秘|機密|極秘|顧客情報|個人情報|口座番号|カード番号|社員番号|契約番号|注文番号)/,/(?:〒?\d{3}[-ー]\d{4})/];if(red.some(p=>p.test(flattened)))return{level:"red",reason:"個人情報・機密情報の可能性があります"};const yellow=[/\d{4,}/,/[A-Za-z]{2,}\d{2,}|\d{2,}[A-Za-z]{2,}/,/(?:株式会社|有限会社|合同会社|部署|部長|課長|担当者|取引先|クライアント|案件|見積|請求)/,/(?:[一-龯々]{2,8})(?:さん|様|くん|君|ちゃん|氏)/];if(yellow.some(p=>p.test(flattened)))return{level:"yellow",reason:"固有情報を含む可能性があります"};return{level:"green",reason:"公開可能な範囲と判定しました"}}
function send(res,status,data){res.statusCode=status;res.setHeader("Content-Type","application/json; charset=utf-8");res.setHeader("Cache-Control","no-store");res.end(JSON.stringify(data))}
function publicItem(item){const{deleteTokenHash,...safe}=item;return safe}
export default async function handler(req,res){try{if(req.method==="GET"){const items=await r2GetJson(INDEX_KEY,[]);return send(res,200,{items:items.slice(0,120).map(publicItem)})}if(req.method==="POST"){const body=typeof req.body==="string"?JSON.parse(req.body||"{}"):req.body||{},text=normalizeText(body.text),check=safetyCheck(text);if(check.level!=="green")return send(res,400,{error:"公開できません",safety:check});if(body.consent!==true)return send(res,400,{error:"公開への同意が必要です"});const style=allowedStyles.has(body.style)?body.style:"business",layout=allowedLayouts.has(body.layout)?body.layout:"horizontal",settings=safeSettings(body.settings),deleteToken=crypto.randomBytes(24).toString("base64url"),item={id:`${Date.now().toString(36)}-${crypto.randomBytes(5).toString("hex")}`,text,style,layout,settings,createdAt:new Date().toISOString(),deleteTokenHash:crypto.createHash("sha256").update(deleteToken).digest("hex")};const current=await r2GetJson(INDEX_KEY,[]);await r2PutJson(INDEX_KEY,[item,...current].slice(0,MAX_ITEMS));return send(res,201,{item:publicItem(item),deleteToken})}if(req.method==="DELETE"){const body=typeof req.body==="string"?JSON.parse(req.body||"{}"):req.body||{},id=String(body.id||""),tokenHash=crypto.createHash("sha256").update(String(body.deleteToken||"")).digest("hex"),current=await r2GetJson(INDEX_KEY,[]),target=current.find(item=>item.id===id);if(!target)return send(res,404,{error:"見つかりません"});if(!crypto.timingSafeEqual(Buffer.from(tokenHash),Buffer.from(target.deleteTokenHash)))return send(res,403,{error:"削除キーが一致しません"});await r2PutJson(INDEX_KEY,current.filter(item=>item.id!==id));return send(res,200,{ok:true})}res.setHeader("Allow","GET, POST, DELETE");return send(res,405,{error:"Method Not Allowed"})}catch(error){console.error("chat-stamps",error);return send(res,500,{error:"処理に失敗しました"})}}
