import { r2GetJson } from "./_r2.js";

const SITE_URL="https://stamp-moke.jp";
function esc(v=""){return String(v).replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function slugify(value=""){return String(value).normalize("NFKC").toLowerCase().trim().replace(/[^a-z0-9\u3040-\u30ff\u3400-\u9fff]+/g,"-").replace(/^-+|-+$/g,"").slice(0,90)}
async function find(slug){return r2GetJson(`free-assets/meta/${slug}.json`,null)}
export default async function handler(req,res){
  try{
    const slug=slugify(req.query.slug||"");const asset=await find(slug);if(!asset||asset.status!=="published"){res.status(404).setHeader("Content-Type","text/html; charset=utf-8").send("<!doctype html><meta charset=utf-8><title>素材が見つかりません | stamp moke</title><p>素材が見つかりません。</p><p><a href=/free/>無料素材一覧へ</a></p>");return}
    const ja=asset.locales?.ja||{};const title=ja.seoTitle||`${ja.title||asset.slug} | 無料フリー素材 | stamp moke`;const description=ja.metaDescription||ja.description||"stamp mokeの個人・非商用向け無料フリー素材です。";const canonical=asset.canonicalUrl||`${SITE_URL}/free/${encodeURIComponent(asset.slug)}`;const previewUrl=`${SITE_URL}/api/free-preview?slug=${encodeURIComponent(asset.slug)}`;
    const tags=[...(asset.platforms||[]),...(asset.types||[]),...(asset.styles||[])].map(x=>`<span>${esc(x)}</span>`).join("");
    const html=`<!doctype html><html lang="ja"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${esc(canonical)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="${esc(previewUrl)}"><meta property="og:type" content="article"><style>:root{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#202124}*{box-sizing:border-box}body{margin:0;background:#fff}.wrap{max-width:900px;margin:auto;padding:28px 16px 80px}.brand{font-weight:900;color:#111;text-decoration:none}.main{display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,.8fr);gap:34px;margin-top:28px}.preview{background:#f5f5f3;border-radius:18px;padding:18px}.preview img{width:100%;display:block;object-fit:contain}.side h1{font-size:30px;line-height:1.35;margin:0 0 10px}.desc{color:#667085;line-height:1.8}.tags{display:flex;flex-wrap:wrap;gap:6px;margin:14px 0}.tags span{font-size:12px;background:#f0f1f2;padding:5px 8px;border-radius:999px}.info{font-size:13px;line-height:1.8;background:#f7f7f5;border-radius:12px;padding:12px 14px;margin:18px 0}.download{display:block;width:100%;border:0;border-radius:13px;padding:15px;background:#111;color:#fff;font-weight:900;font-size:16px;cursor:pointer}.terms{font-size:12px;color:#667085;line-height:1.7;margin-top:12px}.back{margin-top:28px}@media(max-width:700px){.main{grid-template-columns:1fr}.side h1{font-size:24px}}</style></head><body><div class="wrap"><a class="brand" href="/">stamp moke</a><main class="main"><div class="preview"><img src="${esc(previewUrl)}" alt="${esc(ja.alt||ja.title||"無料素材")}"></div><section class="side"><h1>${esc(ja.title||asset.slug)}</h1><p class="desc">${esc(ja.description||"")}</p><div class="tags">${tags}</div><div class="info">${asset.width||"?"} × ${asset.height||"?"}<br>個人利用・非商用利用のみ無料<br>商用利用・再配布・販売・自作発言は禁止<br><strong>著作権 © stamp-moke.jp</strong></div><button class="download" id="download">利用条件に同意してダウンロード</button><p class="terms">ポケカラ、X、Instagram、FacebookなどのSNS、個人プロフィール、壁紙、学校・サークル等の非商用チラシに利用できます。ダウンロード回数には大量取得防止の制限があります。</p></section></main><p class="back"><a href="/free/">← 無料素材一覧へ</a></p></div><script>document.getElementById('download').addEventListener('click',()=>{if(!confirm('個人・非商用利用のみです。商用利用、販売、再配布、自作発言は禁止。著作権は stamp-moke.jp に帰属します。\n\nこの条件に同意してダウンロードしますか？'))return;location.href='/api/free-assets?action=download&agree=1&slug=${encodeURIComponent(asset.slug)}'})</script></body></html>`;
    res.setHeader("Content-Type","text/html; charset=utf-8");res.setHeader("Cache-Control","public, s-maxage=300, stale-while-revalidate=900");res.status(200).send(html);
  }catch(error){console.error(error);res.status(500).send("Internal Server Error")}
}
