import { createRequire } from "node:module";
import { r2GetJson } from "./_r2.js";

const require=createRequire(import.meta.url);
const stickers=require("../src/data/stickers.json");
const phraseMap=require("../src/data/sticker-phrases.json");
const goods=require("../src/data/suzuri-designs.json");
const LOCALES=["ja","en","zh-tw","th","id"];
const clean=(v="")=>String(v).normalize("NFKC").toLowerCase().replace(/\s+/g," ").trim();
const prefix=locale=>locale==="ja"?"":`/${locale}`;
const stripLineTitle=(v="")=>String(v).replace(/\s*-\s*LINE\s*(スタンプ|Stickers?).*$/i,"").trim();
const uniq=a=>[...new Set(a.filter(Boolean).map(String))];
function scoreItem(item,q){const nq=clean(q);if(!nq)return 0;const terms=nq.split(" ").filter(Boolean);const title=clean(item.title),desc=clean(item.description),tags=clean((item.tags||[]).join(" ")),text=clean(item.searchText);let score=0;if(title===nq)score+=160;else if(title.startsWith(nq))score+=90;else if(title.includes(nq))score+=65;if(desc.includes(nq))score+=24;if(tags.includes(nq))score+=30;if(text.includes(nq))score+=12;for(const term of terms){if(title.includes(term))score+=24;if(desc.includes(term))score+=9;if(tags.includes(term))score+=12;if(text.includes(term))score+=4;}return score}
function stickerItems(locale,seoIndex){const seoMap=new Map((Array.isArray(seoIndex)?seoIndex:[]).map(x=>[String(x.id),x]));return stickers.map(s=>{const seo=seoMap.get(String(s.id)),l=seo?.locales?.[locale]||seo?.locales?.ja||{},phrases=phraseMap?.[String(s.id)]?.phrases||[],keywords=l.keywords||[],rels=l.relationships||[],uses=l.uses||[];const title=l.seoTitle||stripLineTitle(s.title);const description=l.metaDescription||s.description||"";return{type:"sticker",id:String(s.id),title,description,image:s.image,url:`${prefix(locale)}/stickers/${s.id}`,tags:uniq([...keywords.slice(0,8),...rels,...phrases.slice(0,6)]).slice(0,12),searchText:[s.title,s.description,l.overview,l.target,l.concept,l.usageIntro,...uses,...rels,...keywords,...phrases,"LINEスタンプ stamp moke"].join(" ")}})}
function freeItems(locale,index){return(Array.isArray(index)?index:[]).filter(a=>a?.status==="published").map(a=>{const l=a.locales?.[locale]||a.locales?.ja||{},tags=uniq([...(a.platforms||[]),...(a.types||[]),...(a.motifs||[]),...(a.styles||[]),...(l.keywords||[])]);return{type:"free",id:String(a.id||a.slug),title:l.title||a.slug,description:l.description||l.metaDescription||"",image:`/api/free-preview?variant=thumb&slug=${encodeURIComponent(a.slug)}`,url:`${prefix(locale)}/free/${encodeURIComponent(a.slug)}`,tags:tags.slice(0,12),searchText:[l.title,l.seoTitle,l.description,l.metaDescription,l.alt,...(l.keywords||[]),...(a.platforms||[]),...(a.types||[]),...(a.motifs||[]),...(a.styles||[]),a.character,"無料 フリー素材 画像 サムネ サムネイル ポケカラ MV PV AI イラスト"].join(" ")}})}
function goodsItems(locale){return(Array.isArray(goods)?goods:[]).map(g=>{const productNames=uniq((g.products||[]).flatMap(p=>[p.itemName,p.title]));const firstUrl=g.products?.[0]?.url||`https://suzuri.jp/bayasihimokei/designs/${g.id}`;return{type:"goods",id:String(g.id),title:g.title||"stamp moke goods",description:g.description||"",image:g.image||g.products?.[0]?.image||"",url:firstUrl,external:true,tags:productNames.slice(0,12),searchText:[g.title,g.description,...productNames,"SUZURI オリジナルグッズ キャラクターグッズ Tシャツ パーカー バッグ ステッカー 雑貨 stamp moke"].join(" ")}})}
export default async function handler(req,res){try{if(req.method!=="GET")return res.status(405).json({error:"Method not allowed"});const q=String(req.query.q||"").slice(0,120),locale=LOCALES.includes(String(req.query.locale||""))?String(req.query.locale):"ja",type=["sticker","free","goods"].includes(String(req.query.type||""))?String(req.query.type):"all";if(clean(q).length<1)return res.status(200).json({query:q,results:[],counts:{all:0,sticker:0,free:0,goods:0}});const[seoIndex,freeIndex]=await Promise.all([r2GetJson("sticker-seo/index.json",[]).catch(()=>[]),r2GetJson("free-assets/index.json",[]).catch(()=>[])]);let items=[...stickerItems(locale,seoIndex),...freeItems(locale,freeIndex),...goodsItems(locale)];const scored=items.map(item=>({...item,score:scoreItem(item,q)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);const counts={sticker:scored.filter(x=>x.type==="sticker").length,free:scored.filter(x=>x.type==="free").length,goods:scored.filter(x=>x.type==="goods").length};counts.all=counts.sticker+counts.free+counts.goods;const results=(type==="all"?scored:scored.filter(x=>x.type===type)).slice(0,80).map(({score,...item})=>item);res.setHeader("Cache-Control","public, s-maxage=60, stale-while-revalidate=300");return res.status(200).json({query:q,results,counts})}catch(error){console.error("site-search",error);return res.status(500).json({error:error instanceof Error?error.message:String(error)})}}
