import { r2GetJson, r2PutJson } from "./_r2.js";

const LOCALES=["ja","en","zh-tw","th","id"];
const key=id=>`sticker-seo/${String(id).replace(/[^0-9]/g,"")}.json`;
const json=(res,status,payload)=>res.status(status).json(payload);
const isAdmin=req=>Boolean(process.env.FREE_ADMIN_TOKEN&&req.headers["x-admin-token"]===process.env.FREE_ADMIN_TOKEN);
function stripFence(v=""){return String(v).trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"")}
function parseJson(v=""){const raw=stripFence(v);try{return JSON.parse(raw)}catch{}const a=raw.indexOf("{"),b=raw.lastIndexOf("}");if(a>=0&&b>a){try{return JSON.parse(raw.slice(a,b+1).replace(/,\s*([}\]])/g,"$1"))}catch{}}return null}
function cleanLocale(v={}){return{overview:String(v.overview||"").slice(0,1800),target:String(v.target||"").slice(0,700),concept:String(v.concept||"").slice(0,700),usageIntro:String(v.usageIntro||"").slice(0,700),uses:[...new Set((Array.isArray(v.uses)?v.uses:[]).map(String).map(x=>x.trim()).filter(Boolean))].slice(0,12),relationships:[...new Set((Array.isArray(v.relationships)?v.relationships:[]).map(String).map(x=>x.trim()).filter(Boolean))].slice(0,10),keywords:[...new Set((Array.isArray(v.keywords)?v.keywords:[]).map(String).map(x=>x.trim()).filter(Boolean))].slice(0,45),metaDescription:String(v.metaDescription||"").slice(0,180)}}
function normalize(raw={},input={}){const locales={};for(const locale of LOCALES)locales[locale]=cleanLocale(raw?.locales?.[locale]||{});return{id:String(input.id||""),version:1,sourceTitle:String(input.title||""),generatedAt:new Date().toISOString(),locales}}
async function callOpenAI(input,extra=""){
 const instruction=`You are an SEO editor for stamp-moke.jp, a Japanese LINE sticker discovery site. Analyze one real sticker set from the supplied title, LINE STORE description, category and detected phrases. Do not invent phrases, characters, demographics or visual facts that are not supported by the supplied data. Write useful natural copy, not keyword stuffing.\n\nFor EACH locale ja,en,zh-tw,th,id, return:\n- overview: a natural 500-1000 character-equivalent introduction explaining the sticker's personality, communication value and why someone would use it.\n- target: who it suits, including relationship/context where supported.\n- concept: the unified concept and emotional/communication job.\n- usageIntro: short lead for use cases.\n- uses: 5-10 concrete situations.\n- relationships: relevant relationship labels.\n- keywords: 20-40 natural search phrases, mixing broad and long-tail terms without repetition.\n- metaDescription: concise search-result description.\n\nLocalized text must be written for searchers in that language, not literal translation. Japanese phrases may remain Japanese when they are actual sticker text. Avoid claims about popularity or sales. Return strictly one JSON object only with shape {\"locales\":{\"ja\":{\"overview\":\"\",\"target\":\"\",\"concept\":\"\",\"usageIntro\":\"\",\"uses\":[],\"relationships\":[],\"keywords\":[],\"metaDescription\":\"\"},\"en\":{},\"zh-tw\":{},\"th\":{},\"id\":{}}}.`;
 const bodyText=`${instruction}\n\nSticker ID: ${input.id}\nTitle: ${input.title}\nLINE STORE description: ${input.description||""}\nCategory: ${input.category||""}\nDetected phrases: ${(input.phrases||[]).join(" / ")||"none"}${extra?`\n\n${extra}`:""}`;
 const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.STICKER_SEO_AI_MODEL||process.env.FREE_ASSET_AI_MODEL||"gpt-5.6-luna",input:bodyText})});
 if(!response.ok)throw new Error(`OpenAI ${response.status}: ${await response.text()}`);
 const data=await response.json();const text=data.output_text||data.output?.flatMap(o=>o.content||[]).find(c=>c.type==="output_text")?.text;if(!text)throw new Error("AI returned no SEO content");return parseJson(text)
}
async function generate(input){let raw=await callOpenAI(input);if(!raw)raw=await callOpenAI(input,"The previous response was invalid JSON. Return the same analysis as strictly valid JSON only.");if(!raw)throw new Error("GPT SEO JSON generation failed twice");return normalize(raw,input)}
export default async function handler(req,res){try{
 const id=String(req.query.id||req.body?.id||"").replace(/[^0-9]/g,"");if(!id)return json(res,400,{error:"Sticker ID is required"});
 if(req.method==="GET"){const record=await r2GetJson(key(id),null);if(!record)return json(res,404,{error:"Not generated"});res.setHeader("Cache-Control","public, s-maxage=300, stale-while-revalidate=1800");return json(res,200,{record})}
 if(req.method!=="POST")return json(res,405,{error:"Method not allowed"});if(!isAdmin(req))return json(res,401,{error:"管理トークンが一致しません。"});if(!process.env.OPENAI_API_KEY)return json(res,500,{error:"OPENAI_API_KEY is not configured"});
 const force=Boolean(req.body?.force),existing=await r2GetJson(key(id),null);if(existing&&!force)return json(res,200,{record:existing,skipped:true});
 const record=await generate({...req.body,id});await r2PutJson(key(id),record);return json(res,200,{record,skipped:false});
}catch(error){console.error("sticker-seo",error);return json(res,500,{error:error instanceof Error?error.message:String(error)})}}
